name: Python Tests

on:
  push: # Run tests on every commit
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint radon

    - name: Run tests
      run: pytest test_merge_sort.py

    - name: running pylint #ocmberi contribution
      continue-on-error: true
      run: |
        mkdir -p post_traces
        pylint hw2_debugging.py rand.py > post_traces/pylint_report.txt

    - name: running radon #mworkuk contribution
      continue-on-error: true
      run: |
        mkdir -p post_traces
        radon cc hw2_debugging.py rand.py > post_traces/radon_report.txt

